################################################################################################
#                             TCDupeFix by iPodHacks142 (iCraft)                               #
#                                  For the 1.6.4 Modpacks                                      #
################################################################################################

################################################################################################
# Crafting Station IDs                                                                         #
################################################################################################
CraftingStationIDs:
  - '2034:*' # Crafting Station Slab
  - '2035:*' # Crafting Station
  
################################################################################################
# Itemduct IDs                                                                                 #
################################################################################################
ItemductIDs: 10714
